apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - infra/k8s/*.yaml
build:
  local:
    push: false
  #googleCloudBuild:
  #  projectId: ticketing-dev-445716
  artifacts:
    - image: trunglinh53/ticketing-dev-client
      #image: us.gcr.io/ticketing-dev-445716/auth
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.tsx'
            dest: .
          - src: 'src/**/*.css'
            dest: .
    - image: trunglinh53/ticketing-dev-auth
      #image: us.gcr.io/ticketing-dev-445716/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: trunglinh53/ticketing-dev-tickets
      #image: us.gcr.io/ticketing-dev-445716/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: trunglinh53/ticketing-dev-orders
      #image: us.gcr.io/ticketing-dev-445716/tickets
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: trunglinh53/ticketing-dev-expiration
      #image: us.gcr.io/ticketing-dev-445716/tickets
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: trunglinh53/ticketing-dev-payments
      #image: us.gcr.io/ticketing-dev-445716/tickets
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
