import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
// import { headers } from 'next/headers';
// import axios from 'axios';

import './globals.css';
import Header from '@/components/layouts/header';
import { AppContextProvider } from '@/contexts/app';
import { getCurrentUser } from '@/query/users';
import { getAllTickets } from '@/query/tickets';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userRes = await getCurrentUser();
  const ticketsRes = await getAllTickets();

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100`}
      >
        <AppContextProvider
          currentUser={userRes.data ? userRes.data.currentUser : null}
          tickets={ticketsRes.data ? ticketsRes.data : []}
        >
          <Header />
          <main className='h-dvh flex justify-center pt-6'>{children}</main>
        </AppContextProvider>
      </body>
    </html>
  );
}
