apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: trunglinh53/ticketing-dev-auth
          #image: us.gcr.io/ticketing-dev-445716/auth
          resources:
            limits:
              memory: 512Mi
              cpu: '0.25'
            requests:
              memory: 256Mi
              cpu: '0.2'
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  #annotations:
  #  cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
